### ISSUE TITLE
Allow for CORS parameters

### ISSUE THREAD

**Issue by ogirardot** [niwinz/django-sse#10]
Hi, first of all thank you for your project, 
it's been really easy to setup a simple SSE based view :)

I've had trouble when i needed to setup my CORS parameters, so i added headers to your "dispatch" method in the base view :

```
    response['Access-Control-Allow-Origin'] = '*'
    response['Access-Control-Allow-Credentials'] = 'true'
```

i don't know how you want to handle it, 
but it's a really important feature that one can change the headers sent easily :)

Regards, 

Olivier.

**Comment by niwinz** [comment]
Hi!

You have a lot of ways to setup coors, you can subclass a view:

```
class SomeView(BaseSseView):
    def dispatch(self, *args, **kwargs):
        response = super(SomeView, self).dispatch(*args, **kwargs)
        response['Access-Control-Allow-Origin'] = '*'
        response['Access-Control-Allow-Credentials'] = 'true'
        return response
```

Also you can create it as decorator to make more reusable code, or you can put a global middleware for a coors like this: https://gist.github.com/niwibe/5280503

**Comment by ogirardot** [comment]
nice thx, 
i'll try it out :)
