### ISSUE TITLE
Allow using django database as message queue

### ISSUE THREAD

**Issue by odinho** [niwinz/django-sse#16]
For small sites (which I guess is most) it'd make sense to not relying on Redis (or RabbitMQ) as a queue. Kinda like Celery allows you to use the database you already have for django.

Ofc, it would have to poll, but that's okay for such a simple deployment.

It would make developing sites simpler too, hopefully. WDYT?

**Comment by odinho** [comment]
Potentially using Kombu as Celery is, then it can use Redis and RabbitMQ and a host of others in addition to Django ORM or SQLAlchemy for small setups.

https://pypi.python.org/pypi/kombu

**Comment by niwinz** [comment]
This project is unmaintained. Sorry for inconvenience.
