### ISSUE TITLE
Is there a way to support heartbeat responses?

### ISSUE THREAD

**Issue by Novarg** [niwinz/django-sse#19]
Is there a way to support heartbeat responses? Let's say print some dummy data into streams each 30 sec to not allow browser to close connection for longer time? (IE ignores timeout value in keep-alive header). I'm thinking that expiration of heartbeat should be set in settings to support longer requests or turn that off and rely on browser completely.

I'm currently using heartbeat middleware for such purposes but maybe it can be done on django-sse level automatically and more elegant?

**Comment by niwinz** [comment]
This project is unmaintained. Sorry for inconvenience.
