### ISSUE TITLE
Runserver doesn't reload with an active SSE connection

### ISSUE THREAD

**Issue by ipmb** [niwinz/django-sse#8]
Longpolling seems to prevent runserver from restarting cleanly during development (using Django 1.4). It'd be nice to have it kill open connections so it can reload properly. Not sure if this is an issue upstream or something that `django-sse` can workaround.

**Comment by niwinz** [comment]
Hello!
With django 1.4 has introduced support for multithreading to runserver and the bug you mention this not only happens with django-sse. It also happens in many ocaciociones, when you have many requests (especially when you serve static in development environment with runserver).

In the part of django-sse can not do much.

Andrey
